---
- name: Testing andrewrothstein.nats_server
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'nats-server --version'
      ansible.builtin.command: /usr/local/nats-server/nats-server --version
      changed_when: false
      register: nats_server_output
    - name: Output of 'nats-server --version'
      ansible.builtin.debug:
        msg: '{{ nats_server_output.stdout }}'
